# Generated by Django 5.2.1 on 2025-05-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_questions_correct_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='correct_option',
            field=models.IntegerField(),
        ),
    ]
