# Generated by Django 5.2.1 on 2025-05-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_profile_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='answer',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='question',
            field=models.CharField(default='?', max_length=200),
        ),
    ]
