# Generated by Django 5.2.1 on 2025-05-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_profile_answer_profile_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='answer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='question',
            field=models.CharField(max_length=200),
        ),
    ]
