# Generated by Django 5.2.1 on 2025-05-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_profile_answer_alter_profile_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='score',
            new_name='easy_score',
        ),
        migrations.AddField(
            model_name='profile',
            name='hard_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='medium_score',
            field=models.IntegerField(default=0),
        ),
    ]
